version: 2
jobs:
  deploy_prod:
    docker:
      - image: circleci/node:12.15.0
    working_directory: ~/arb-token-bridge
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ checksum "package.json" }}
      - run:
          name: Deploy Prod
          command: |
            yarn build
            ssh -oStrictHostKeyChecking=no hkalodner@206.189.196.195 "rm -rf /var/www/developer.offchainlabs.com/html/tools/tokenbridge/local*"
            scp -oStrictHostKeyChecking=no -r dist/* hkalodner@206.189.196.195:/var/www/developer.offchainlabs.com/html/tools/tokenbridge/local

workflows:
  version: 2
  deploy:
    jobs:
      - deploy_prod:
          filters:
            branches:
              only: master
